# -*- coding: utf-8 -*-
"""smlrun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PNRA7lZNT56X6LKdihBWquCZv5si-Gsx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re


import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from gensim.models import Word2Vec


from collections import Counter
import string
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import spacy


import xgboost as xgb
from hyperopt import fmin, hp, tpe


from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report


import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Masking
from keras.layers import LSTM, Dense, Masking, SimpleRNN, StackedRNNCells, GRU, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.optimizers import Adam # - Works



from transformers import BertTokenizer, BertModel
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense
import torch

df_sentence = pd.read_csv('train.csv')

df_sentence['label_boolean'] = df_sentence['label_boolean'].astype(int)
nlp = spacy.load('en_core_web_sm')
def spacy_lemmatize(text):
    text=text.lower()
    text = re.sub(r'\?+', '?', text)
    text = re.sub(r'\!+', '!', text)
    text = re.sub(r'\/+', '', text)
    text = re.sub(r'`', '', text)
    text = re.sub(r'-lrb-', '-', text)
    text = re.sub(r'-rrb-', '-', text)
    text = re.sub(r'\-+', '-', text)
    text = re.sub(r"I've", "i have", text)
    text = re.sub(r"i've", "i have", text)
    text = re.sub(r"I'm", "i am", text)
    text = re.sub(r"i'm", "i am", text)
    text = re.sub(r" - ", " . ", text)
    text = re.sub(r"i 'm", "i am", text)
    text = re.sub(r"i 've", "i have", text)
    doc = nlp(text)
    lemmatized_tokens = [token.lemma_ for token in doc]
    lemmatized_text = ' '.join(lemmatized_tokens)
    lemmatized_text = re.sub(r"'s\b", "s", lemmatized_text)
    return lemmatized_text
df_sentence['lemmatized_text'] = df_sentence['text'].apply(spacy_lemmatize)
important_sentences = []

for index, row in df_sentence.iterrows():
    text = ""  # Initialize an empty string

    if row['metaphorID'] == 0:
        keyword_search = 'road'
    elif row['metaphorID'] == 1:
        keyword_search = 'candle'
    elif row['metaphorID'] == 2:
        keyword_search = 'light'
    elif row['metaphorID'] == 3:
        keyword_search = 'spice'
    elif row['metaphorID'] == 4:
        keyword_search = 'ride'
    elif row['metaphorID'] == 5:
        keyword_search = 'train'
    elif row['metaphorID'] == 6:
        keyword_search = 'boat'

    for j in row['lemmatized_text'].split('.'):



        if keyword_search in j:
            if (' - ' not in j) and (' , ' not in j) and (' ; ' not in j) and (' ? ' not in j) and (' ! ' not in j):
                if keyword_search in j:
                        text = j
                        break

            elif ' , ' in j:
                for k in j.split(','):
                    if keyword_search in k:
                        text = k
                        break
            elif ' ; ' in j:
                for k in j.split(';'):
                    if keyword_search in k:
                        text = k
                        break
            elif ' ? ' in j:
                for k in j.split(' ? '):
                    if keyword_search in k:
                        text = k
                        break
            elif ' ! ' in j:
                for k in j.split(' ! '):
                    if keyword_search in k:
                        text = k
                        break
            elif ' - ' in j:
                for k in j.split(' - '):
                    if keyword_search in k:
                        text = k
                        break

    if text:
        important_sentences.append(text)
df_important_sentence = pd.DataFrame({'important_sentences': important_sentences})
df_sentence['important_sentences']=df_important_sentence['important_sentences']

X = df_sentence['important_sentences'].to_list()
y = df_sentence["label_boolean"].to_list()


# split into train test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=1, stratify=y)

import pandas as pd

data = {
    'Sentences': [
        "We took a detour because of road construction on our way to the grocery store.",
        "I got stuck in traffic on the road during rush hour, and it was so frustrating.",
        "The road was so bumpy that it made the car ride uncomfortable.",
        "I love going on road trips with my friends; it's always an adventure.",
        "The road to success is often challenging, but the journey is worth it.",
        "I need to check the road conditions before heading out because of the recent snowfall.",
        "My GPS always finds the fastest route to avoid heavy traffic on the road.",
        "We had a picnic by the side of the road and enjoyed the scenic view.",
        "The road signs were confusing, and I almost missed my turn.",
        "I take the scenic route whenever possible to enjoy the beauty along the road.",
        "There was a road closure due to a marathon, and it messed up my morning commute.",
        "I always keep an emergency kit in my car, just in case I get stranded on the road.",
        "The road trip playlist made the journey more enjoyable.",
        "I had to pull over because my car was making strange noises on the road.",
        "The road ahead was foggy, and visibility was low.",
        "I love driving on winding roads; it's so much fun!",
        "I missed the exit and had to take a U-turn to get back on the right road.",
        "The road to the beach was lined with palm trees, creating a tropical vibe.",
        "I always follow the speed limit to ensure a safe journey on the road.",
        "The road was deserted, and I felt a bit uneasy driving alone at night.",
        "We hit a pothole on the road, and it gave us quite a jolt.",
        "The road trip was exhausting, but the memories made it worthwhile.",
        "I need to schedule a maintenance check for my car before hitting the road.",
        "The road was flooded due to heavy rain, so we had to take a different route.",
        "I enjoy taking the scenic route and exploring new roads in the countryside.",
        "The road to my friend's house was blocked, so I had to find an alternate way.",
        "I always keep a paper map in my glove compartment in case I lose GPS signal on the road.",
        "The road trip was filled with laughter, snacks, and good music.",
        "The road was narrow, and I had to be extra cautious while driving through the hills.",
        "I encountered a roadblock and had to wait for the construction crew to clear the debris.",
        "The road was icy, so I had to drive slowly to avoid slipping.",
        "I spotted a quaint cafe by the side of the road and decided to stop for a cup of coffee.",
        "The road to the national park was scenic, with lush greenery on both sides.",
        "I prefer taking the back roads to avoid the hustle and bustle of the main highway.",
        "The road trip was a great opportunity to bond with my family.",
        "I always keep an eye on the gas gauge to ensure I don't run out of fuel on the road.",
        "The road was steep, and the car struggled a bit to climb the hill.",
        "I enjoyed the road trip despite the occasional rain showers.",
        "I saw a beautiful sunset while driving on the coastal road.",
        "The road was blocked due to a parade, causing a traffic jam.",
        "I discovered a charming bookstore on a quaint road during my travels.",
        "The road trip was a much-needed break from the routine.",
        "I encountered a road sign indicating a detour, so I followed the alternate route.",
        "The road to the airport was clear, and I reached well ahead of time.",
        "I always pack a cooler with snacks for the road trip.",
        "The road trip with friends was filled with laughter, stories, and fun games.",
        "I spotted a deer crossing the road, so I slowed down to let it pass safely.",
        "The road was windy, making the drive through the mountains exhilarating.",
        "I had to change a flat tire on the side of the road; thankfully, I had a spare.",
        "The road to the beach was lined with colorful wildflowers.",
        "I encountered a road sign warning of deer in the area, so I drove cautiously.",
        "The road trip playlist included all our favorite songs.",
        "I took a scenic detour and discovered a charming little village off the main road.",
        "The road conditions were treacherous during the snowstorm, so I drove carefully.",
        "I enjoy the solitude of driving on quiet country roads.",
        "The road was under repair, and I had to navigate through a maze of cones.",
        "I always carry a first aid kit in my car in case of emergencies on the road.",
        "The road trip was a great opportunity to explore new places and try local cuisine.",
        "I had to pull over and ask for directions when I realized I was on the wrong road.",
        "The road to the countryside was scenic, with rolling hills and open fields.",
        "I took a shortcut, but it turned out to be a bumpy dirt road.",
        "The road trip provided a chance to admire the changing landscapes.",
        "I spotted a roadside diner and decided to stop for a quick meal during the journey.",
        "The road was blocked due to a fallen tree, so I had to find an alternate route.",
        "I always check the weather forecast before embarking on a long road trip.",
        "The road to the mountain summit was steep, but the view from the top was breathtaking.",
        "I encountered a road sign indicating a wildlife sanctuary, so I kept an eye out for animals.",
        "The road trip with my family included scenic overlooks and photo stops.",
        "I drove through a quaint village with cobblestone streets on my way to the countryside.",
        "The road was narrow, and I had to yield to oncoming traffic.",
        "I encountered a road closure due to a marathon, so I had to find an alternate route.",
        "I always carry a spare tire and tools for minor repairs on the road.",
        "The road to the beach was lined with palm trees, creating a tropical vibe.",
        "I enjoy driving on winding roads; it's so much fun!",
        "I missed the exit and had to take a U-turn to get back on the right road.",
        "The road to the mountain summit was steep, but the view from the top was breathtaking.",
        "I encountered a road sign indicating a wildlife sanctuary, so I kept an eye out for animals.",
        "The road trip with my family included scenic overlooks and photo stops.",
        "I drove through a quaint village with cobblestone streets on my way to the countryside.",
        "The road was narrow, and I had to yield to oncoming traffic.",
        "I encountered a road closure due to a marathon, so I had to find an alternate route.",
        "I always carry a spare tire and tools for minor repairs on the road.",
        "The road to the beach was lined with palm trees, creating a tropical vibe.",
        "I enjoy driving on winding roads; it's so much fun!",
        "The road stretches ahead for miles.",
    "The road is narrow and winding through the mountains.",
    "Road construction is causing delays for commuters.",
    "Drivers should obey the speed limit on the road.",
    "The road is lined with ancient trees on either side.",
    "A pedestrian is crossing the road at the crosswalk.",
    "The road is well-lit with streetlights at night.",
    "Cyclists share the road with motorists.",
    "Road maintenance is essential for a smooth driving experience.",
    "The road forks, and drivers must choose the correct lane.",
    "The road leads to a bustling city.",
    "A rural road meanders through picturesque farmland.",
    "The road is straight and flat in this part of the country.",
    "Road signs provide directions for drivers.",
    "The road narrows as it passes through the old town.",
    "Heavy rain can create puddles on the road.",
    "Drivers should be cautious on icy roads during winter.",
    "The road is flanked by open fields on both sides.",
    "Traffic lights control the flow of vehicles on the road.",
    "The road is undergoing repairs due to potholes.",
    "A bridge spans over the river, connecting two roads.",
    "The road curves gently around the serene lake.",
    "A long line of cars is stuck in traffic on the road.",
    "The road is the main artery of transportation in the region.",
    "Motorcycles zoom past on the open road.",
    "The road is bumpy in the rural countryside.",
    "A straight road is easier to navigate for new drivers.",
    "The road is deserted in the early hours of the morning.",
    "Drivers should yield to pedestrians at crosswalks on the road.",
    "A detour sign directs traffic away from the main road.",
    "The road winds through a dense forest.",
    "The road is divided into multiple lanes for different speeds.",
    "A small town is nestled along the road.",
    "The road is well-maintained with fresh asphalt.",
    "An old windmill stands by the side of the road.",
    "The road cuts through the heart of the urban landscape.",
    "A stop sign controls traffic at the intersection of two roads.",
    "The road is steep, requiring careful navigation.",
    "A cyclist is pedaling vigorously on the hilly road.",
    "The road is busy with the hustle and bustle of city life.",
    "A traffic jam has brought the road to a standstill.",
    "The road passes by a serene lake with swans.",
    "A road trip offers a sense of adventure and discovery.",
    "The road divides, leading to different neighborhoods.",
    "Drivers should watch for deer crossing the road in rural areas.",
    "The road is bordered by quaint shops and cafes.",
    "A roundabout controls traffic flow at a busy road junction.",
    "The road is surrounded by rolling hills and farmland.",
    "A highway interchange connects multiple roads.",
    "The road is part of a scenic route with breathtaking views.",
    "A motorist is changing a flat tire on the side of the road.",
    "The road is quiet in the late hours of the night.",
    "Traffic congestion is a common issue on the road.",
    "A road trip is a great way to explore the countryside.",
    "The road is well-marked with painted lines.",
    "A speed bump slows down drivers on a residential road.",
    "The road leads to a historic village.",
    "A long and straight road stretches into the distance.",
    "The road is enveloped in fog on a misty morning.",
    "A traffic officer directs vehicles at a busy road junction.",
    "The road is surrounded by tall skyscrapers in the city.",
    "A road closure requires a detour for drivers.",
    "The road passes through a vibrant urban neighborhood.",
    "A road atlas is a useful tool for long-distance travelers.",
    "The road is a lifeline for remote villages.",
    "A toll booth collects fees for using the highway.",
    "The road twists and turns through a mountain pass.",
    "A zebra crossing provides a safe passage for pedestrians on the road.",
    "The road is bordered by colorful flowers in the spring.",
    "A road trip playlist enhances the driving experience.",
    "The road is divided by a median strip.",
    "A pothole in the road poses a risk to drivers.",
    "The road is quiet during the early hours of the day.",
    "A road map helps navigate unfamiliar terrain.",
    "The road is busy with trucks transporting goods.",
    "A road closure sign indicates construction ahead.",
    "The road is flanked by residential houses.",
    "A car is parked along the side of the road.",
    "The road is well-maintained with regular repairs.",
    "A pedestrian bridge spans over the busy road.",
    "The road is illuminated by the headlights of passing cars.",
    "A road trip provides an opportunity for bonding with friends.",
    "The road is surrounded by lush greenery."
   ],
   'Label':0,
   'Metaphor_ID':0

}

df_road_no_metaphor = pd.DataFrame(data)



data = {
    'Sentences': [
        "I light a candle and say a prayer for my friend who is going through a difficult time.",
        "After hearing the news, I immediately lit a candle and offered my condolences in silent prayer.",
        "In times of sorrow, I light a candle to send my heartfelt condolences and prayers to those affected.",
        "I light a candle and reflect on the memories of a loved one, sending my thoughts and prayers to the grieving family.",
        "Learning about the tragedy, I lit a candle to express my condolences and prayed for strength for the affected families.",
        "In moments of sadness, I light a candle for comfort and offer my sincere prayers for healing and peace.",
        "Receiving the news of the loss, I lit a candle to honor the departed soul and prayed for solace for their loved ones.",
        "I always light a candle when offering condolences, a small gesture to accompany my heartfelt prayers.",
        "Hearing about your loss, I immediately lit a candle and whispered a prayer for you and your family.",
        "I light a candle for those facing adversity, sending my prayers for strength, resilience, and healing.",
        "In times of grief, I light a candle and extend my deepest condolences, accompanied by heartfelt prayers.",
        "I received the sad news and, in response, lit a candle to offer my condolences and send comforting prayers.",
        "I light a candle for you, my friend, offering prayers of strength, courage, and comfort during this challenging time.",
        "Learning about the difficult situation, I lit a candle and offered silent prayers for guidance and support.",
        "I always light a candle when expressing condolences, a symbol of my sincere thoughts and prayers.",
        "Hearing about your struggles, I immediately lit a candle and prayed for you, sending comfort and strength.",
        "In moments of loss, I light a candle and send my heartfelt condolences through silent prayers.",
        "I lit a candle and prayed for peace and strength to surround you during this time of sorrow.",
        "I always light a candle when offering condolences, a small ritual to accompany my thoughts and prayers.",
        "Hearing about the challenges you're facing, I lit a candle and offered my sincere condolences through prayer.",
        "I light a candle for comfort, solace, and strength, sending my prayers to those in need.",
        "In times of hardship, I light a candle to accompany my heartfelt prayers for healing and resilience.",
        "Receiving the sad news, I immediately lit a candle and prayed for you, offering my deepest condolences.",
        "I always light a candle when expressing condolences, a symbolic gesture of my thoughts and prayers.",
        "Hearing about your loss, I lit a candle and offered my condolences through silent and heartfelt prayers.",
        "I light a candle and pray for the departed soul, sending condolences and comfort to the grieving family.",
        "In times of sorrow, I light a candle and extend my deepest condolences, accompanied by heartfelt prayers.",
        "Learning about the difficult situation, I lit a candle and offered silent prayers for guidance and support.",
        "I always light a candle when expressing condolences, a symbol of my sincere thoughts and prayers.",
        "Hearing about your struggles, I immediately lit a candle and prayed for you, sending comfort and strength.",
        "In moments of loss, I light a candle and send my heartfelt condolences through silent prayers.",
        "I lit a candle and prayed for peace and strength to surround you during this time of sorrow.",
        "I always light a candle when offering condolences, a small ritual to accompany my thoughts and prayers.",
        "Hearing about the challenges you're facing, I lit a candle and offered my sincere condolences through prayer.",
        "I light a candle for comfort, solace, and strength, sending my prayers to those in need.",
        "In times of hardship, I light a candle to accompany my heartfelt prayers for healing and resilience.",
        "Receiving the sad news, I immediately lit a candle and prayed for you, offering my deepest condolences.",
        "I always light a candle when expressing condolences, a symbolic gesture of my thoughts and prayers.",
        "Hearing about your loss, I lit a candle and offered my condolences through silent and heartfelt prayers.",
        "I light a candle and pray for the departed soul, sending condolences and comfort to the grieving family."
		"I lit a candle to create a cozy atmosphere while reading my book.",
        "My friend gave me scented candles as a birthday gift, and they smell amazing.",
        "I bought a new candle holder to display my favorite candles in the living room.",
        "After a long day at work, I love to unwind by lighting a scented candle.",
        "I placed a candle on the dining table to add a touch of elegance to our dinner.",
        "During the power outage, we relied on candles to light up the room.",
        "I found a unique handmade candle at the local market, and it's now my favorite.",
		"I light a candle on my desk when I need to focus and create a calming work environment.",
        "I brought scented candles to my friend's housewarming party as a thoughtful gift.",
        "I always light a candle when I'm writing in my journal; it helps me concentrate.",
        "I have a collection of vintage candle holders that I display on my mantelpiece.",
        "I enjoy the ritual of lighting a candle before starting my meditation practice.",
        "I use scented candles with lavender fragrance to promote relaxation and better sleep.",
    ],
	'Label':0,
	'Metaphor_ID':1
}

df_no_metaphor_candle = pd.DataFrame(data)




data = {
    'Sentences': [
        "Lately, I feel like I'm burning the candle at both ends, juggling work and personal life with a fiery intensity.",
        "With the project deadline looming, I find myself burning the midnight oil, the candle's flame flickering against the darkness of the night.",
        "Life has been throwing curveballs, and I'm juggling so much that it feels like I'm burning the candle at both ends.",
        "The hustle and bustle of city life have me burning the candle at both ends, leaving me yearning for a moment of tranquility.",
        "In the chaos of daily demands, it seems like I'm burning the candle from both ends, chasing after deadlines and dreams.",
        "Balancing family, work, and personal goals can feel like burning the candle at both ends, yet the glow keeps me going.",
        "The whirlwind of responsibilities has me feeling like I'm burning the candle at both ends, trying to keep up with the pace.",
        "Navigating the challenges of life sometimes feels like burning the candle at both ends, with each flame representing a different responsibility.",
        "As the weeks go by, I sense myself burning the candle at both ends, pouring energy into various aspects of life.",
        "Juggling multiple roles can be exhausting; it's like burning the candle at both ends and hoping the light doesn't fade too soon.",
        "The demands of my dual roles at work and home make it seem like I'm burning the candle at both ends, trying to keep the flames alive.",
        "In the hustle of daily life, it feels as if I'm burning the candle at both ends, chasing dreams while managing the mundane.",
        "As I tackle the challenges before me, it's like burning the candle at both ends, with each task contributing to the overall glow.",
        "The intensity of my schedule has me burning the candle at both ends, striving to find a balance between work and self-care.",
        "Life's complexities sometimes lead to burning the candle at both ends, but I find solace in the warmth of the journey.",
        "Striking a balance between career and personal life often feels like burning the candle at both ends, yet the light keeps me moving forward.",
        "In the hustle of daily commitments, it's akin to burning the candle at both ends, seeking moments of respite in the flickering glow.",
        "The dual responsibilities have me burning the candle at both ends, the flames dancing in harmony with the rhythm of life.",
        "Managing the challenges of adulthood sometimes feels like burning the candle at both ends, a delicate dance between responsibilities.",
        "The constant demands of life have me burning the candle at both ends, finding strength in the flickering flames of resilience.",
        "As I navigate the complexities of my schedule, it's like burning the candle at both ends, each task contributing to the collective glow.",
        "Juggling priorities and commitments can be overwhelming, akin to burning the candle at both ends and hoping the flame endures.",
        "The pressure to excel in multiple arenas has me burning the candle at both ends, finding strength in the luminosity of determination.",
        "Striving for a work-life balance feels like burning the candle at both ends, a delicate dance between professional aspirations and personal fulfillment.",
        "Navigating the intricacies of daily life is akin to burning the candle at both ends, with each challenge adding to the vibrant tapestry of experience.",
        "As I tackle the challenges of each day, it feels like burning the candle at both ends, the flame resilient against the winds of adversity.",
        "Juggling responsibilities is like burning the candle at both ends, a delicate balance between illumination and potential exhaustion.",
        "In the pursuit of dreams and aspirations, it often feels like burning the candle at both ends, with the flame representing unwavering determination.",
        "The ebb and flow of life's demands can be exhausting, akin to burning the candle at both ends and hoping for moments of respite.",
        "Striking a balance between career aspirations and personal well-being is like burning the candle at both ends, a dance between ambition and self-care.",
        "As I strive to meet deadlines and obligations, it feels like burning the candle at both ends, the flame resilient against the passage of time.",
        "The intricacies of daily life have me burning the candle at both ends, with the flames casting shadows that dance along the journey.",
        "Navigating the twists and turns of life feels like burning the candle at both ends, the flame a testament to resilience in the face of challenges.",
        "In the pursuit of personal and professional growth, it's like burning the candle at both ends, with each challenge contributing to the radiant glow.",
        "Juggling the responsibilities of work and personal life is akin to burning the candle at both ends, a delicate balance between dedication and self-care.",
        "The journey of self-discovery often involves burning the candle at both ends, the flames illuminating the path to personal fulfillment.",
        "As I strive for excellence in various facets of life, it feels like burning the candle at both ends, with the flames casting a warm and determined glow.",
        "The relentless pursuit of goals and aspirations has me burning the candle at both ends, finding strength in the enduring flame of ambition."
		"Facing the challenges of treatment is like holding a candle in the dark, searching for hope amidst the shadows.",
        "The journey through chemotherapy feels like walking a path illuminated by a flickering candle, each step a testament to resilience.",
        "In the midst of uncertainty, we share our experiences like passing a candle, lighting the way for others in the cancer journey.",
        "Coping with side effects often feels like balancing a delicate candle, trying to keep the flame of positivity burning.",
        "Radiation therapy can be like navigating through a maze with a candle, finding strength in the warmth of support from fellow warriors.",
        "When discussing treatment options, it's like examining a candle, exploring the different facets of hope and healing.",
        "Support groups are a bit like a circle of candles; each participant's story contributes to the collective glow of understanding.",
        "Sharing survival stories in the chat room is like passing a candle, illuminating the path for those currently in the throes of treatment.",
        "Dealing with setbacks can be akin to trying to relight a candle in the wind, the challenges threatening to extinguish our spirit.",
        "The process of healing is like tending to a fragile candle, nurturing hope and strength through the ups and downs.",
        "Expressing our fears and hopes is like lighting a candle in the heart, illuminating the emotions that often remain in the shadows.",
        "We find solace in each other's words, a bit like finding a familiar candle in the darkness of uncertainty.",
        "When discussing remission, it's like holding a candle in the wind, cautiously protecting the flame of newfound hope.",
        "Offering advice on managing symptoms is akin to sharing the light of a well-burning candle, passing on practical wisdom.",
        "Navigating the intricacies of treatment options feels like choosing the right candle, each one representing a unique path to healing.",
        "Cancer survivors are beacons of hope, like candles burning brightly, casting a warm glow on the possibilities beyond diagnosis.",
        "Supportive friendships are like candles in the dark, providing comfort and companionship on the challenging journey.",
        "Exploring complementary therapies can be like finding an additional candle, casting different hues on the canvas of healing.",
        "In the face of uncertainty, our shared stories become candles in the night, collectively dispelling the darkness of fear.",
        "When facing the unknown, discussing clinical trials is like considering a new type of candle, a potential source of light in the darkness.",
        "Managing treatment side effects is like carefully tending to a delicate candle, ensuring it continues to burn with resilience.",
        "In the chat room, words of encouragement are exchanged like candles, passing the flame of support from one person to another.",
        "Celebrating small victories feels like lighting a candle in the midst of a storm, finding joy despite the challenges.",
        "Reflecting on the journey is akin to observing a burning candle, each flicker representing moments of strength, courage, and hope.",
    ],
	'Label':1,
	'Metaphor_ID':1
}

df_candle_metaphor = pd.DataFrame(data)






data = {
    'Sentences': [
        "Facing a chronic illness can be like losing the spice of life, as it challenges the vibrancy we once knew.",
        "Dealing with setbacks in treatment often feels like a recipe missing its spice, leaving the journey with a bit less flavor.",
        "Surviving a major surgery feels like reclaiming the spice of life, a triumphant return to normalcy.",
        "Discussing the challenges of treatment in public can be like adding an unexpected spice to the conversation, catching some off guard.",
        "Navigating the complexities of a medical diagnosis is like trying to find the right spice in a vast pantry of emotions.",
        "Sharing experiences in the chemo room is akin to swapping spice blends, each story adding a unique flavor to the collective conversation.",
        "Reflecting on the impact of illness is like realizing the absence of a beloved spice, a subtle but profound loss.",
        "The unpredictability of health can be likened to a dish missing a key spice, altering the expected flavor of life.",
        "Discussing intimate topics in a public setting can be like adding a surprising spice to the conversation, catching some by surprise.",
        "Support groups bring together various stories, each one contributing a distinct spice to the tapestry of shared experiences.",
        "Facing challenges with a sense of humor is like adding a pinch of spice to the seriousness of illness, lightening the emotional load.",
        "Exploring treatment options can be compared to selecting the right spice for a recipe, each choice influencing the overall flavor of recovery.",
        "Survivorship is akin to rediscovering the spice of life, savoring each moment with newfound appreciation.",
        "Expressing emotions openly is like adding a necessary spice to the conversation, enhancing the depth of connection in the community.",
        "The resilience of the human spirit can be likened to a secret spice, infusing strength into the challenges of the health journey.",
        "Sharing coping mechanisms is like exchanging recipes for a well-seasoned life, each tip contributing a valuable spice to the mix.",
        "Facing fears and uncertainties is like adding an unexpected spice to the journey, a bold flavor challenging the status quo.",
        "Discussing personal matters openly is like sharing the secret spice of relationships, deepening connections in unexpected ways.",
        "Supportive friendships are like the perfect spice blend, enhancing the flavors of life during challenging times.",
        "Finding joy in the small victories is akin to discovering a hidden spice, adding sweetness to the bitter moments.",
        "Facing adversity with resilience is like mastering the art of cooking with a versatile spice, adapting to various challenges.",
        "Navigating the emotional landscape of illness is like experimenting with a new spice, discovering its impact on the overall flavor of life.",
        "The unpredictability of a health journey can be like an unexpected spice, surprising us with both challenges and moments of resilience.",
        "Expressing vulnerability is like adding a necessary spice to the conversation, creating a space for authentic connection.",
        "Facing a medical diagnosis is like discovering a missing spice in the recipe of life, prompting us to adapt and find new flavors.",
        "Sharing stories of hope is like passing along a cherished spice, adding a sprinkle of encouragement to those in need.",
        "The ups and downs of treatment can be likened to the ebb and flow of a spice, influencing the overall taste of the health journey.",
        "Surviving challenges is like retaining the spice of life, a testament to resilience and the ability to overcome adversity.",
        "Expressing gratitude is like seasoning life with a positive spice, enhancing the overall flavor of the journey.",
        "Sharing laughter in the face of adversity is like adding a dash of spice to the moment, transforming the atmosphere.",
        "Discussing treatment options is like exploring a variety of spice blends, each approach offering a unique flavor to the healing process.",
        "Support groups provide a space for participants to share their unique spice, contributing to the collective richness of experiences.",
        "The journey through illness can be compared to experimenting with a new spice, adapting to its nuances and finding ways to appreciate the flavor.",
        "Navigating the unknowns of treatment is like crafting a new recipe, each decision influencing the overall spice of the healing process.",
        "Discussing life after treatment is like considering the right spice for a dish, contemplating the flavors of a renewed and resilient existence.",
        "Sharing personal victories is akin to passing along a secret spice, inspiring others to savor the sweetness of overcoming challenges.",
        "Reflecting on the journey is like savoring the blend of spices in a well-cooked dish, appreciating the unique flavor each challenge brings.",
        "Expressing empathy in the face of adversity is like adding a soothing spice to the conversation, offering comfort and understanding.",
        "Sharing advice on managing symptoms is akin to passing along a well-loved spice recipe, each tip contributing to the overall flavor of resilience."
		"I wanted to spice things up in my daily routine.",
    "Adding a new hobby to my life helped spice things up.",
    "Exploring different activities is a great way to spice things up.",
    "I decided to spice things up by trying new experiences.",
    "Spicing up my life with a positive mindset made a significant difference.",
    "Every now and then, it's important to spice things up for mental well-being.",
    "I've been trying to find ways to spice things up and make each day special.",
    "Finding joy in simple pleasures is a wonderful way to spice things up.",
    "Spicing things up with laughter is my favorite therapy.",
    "I made a conscious effort to spice things up by embracing change.",
    "Trying new flavors and cuisines is a delicious way to spice things up.",
    "Incorporating creativity into my routine has helped spice things up.",
    "To enhance my well-being, I decided to spice things up with more social interactions.",
    "I wanted to spice things up, so I started a new adventure.",
    "Spicing up my life with positivity and gratitude has been transformative.",
    "I realized the importance of spicing things up to break the monotony.",
    "Taking spontaneous trips is a fantastic way to spice things up.",
    "Spicing things up with music and dance brings so much joy.",
    "I've learned that small changes can spice things up in a big way.",
    "Adding variety to my meals has been a tasty way to spice things up.",
    "Spicing things up with a touch of spontaneity adds excitement to life.",
    "I made it a goal to spice things up by trying something new each week.",
    "Changing my perspective has been a powerful way to spice things up.",
    "Spicing up my routine with moments of mindfulness has been refreshing.",
    "I decided to spice things up by rediscovering old passions.",
    "Embracing new challenges has been an effective way to spice things up.",
    "I've been on a mission to spice things up and make life more vibrant.",
    "Spicing things up with a positive attitude has made a world of difference.",
    "Introducing variety into my daily activities has helped spice things up.",
    "I've been actively seeking opportunities to spice things up and savor life.",
    "Spicing things up by stepping out of my comfort zone has been invigorating.",
    "I realized the importance of spicing things up to keep life interesting.",
    "Trying different cuisines has been a delightful way to spice things up.",
    "I've been on a quest to spice things up and make life more flavorful.",
    "Spicing up my routine with small adventures has added excitement to my days.",
    "Introducing surprises into my routine has been a fun way to spice things up.",
    "I wanted to spice things up, so I embraced the beauty of spontaneity.",
    "Spicing up my life with moments of joy has been a transformative experience.",
    "I've been exploring new hobbies as a way to spice things up.",
    "Adding a dash of creativity to my routine has helped spice things up.",
    "Spicing things up with positive affirmations has improved my outlook on life.",
    "I made a conscious effort to spice things up and bring more joy into my days.",
    "Embracing change has been a powerful way to spice things up in my life.",
    "I've been on a mission to spice things up and make every moment count."
    ],
	'Label':1,
	'Metaphor_ID':3
}

# Create a DataFrame with a "Label" column set to 1 for metaphors
df_patient_metaphors_spice = pd.DataFrame(data)

# Display the DataFrame




data = {
    'Sentences': [
        "Turmeric is a wonderful natural spice that might interfere with chemotherapy resistance, but its effects may be limited to the gut wall.",
        "For a light meal during chemo, try chicken soup, crackers, toast, or noodle-based dishes without too much sauce or spices.",
        "Curcumin, found in turmeric, is a beneficial natural spice that may interfere with chemotherapy resistance, although its effects are mostly limited to the gut wall.",
        "Sometimes I find the ice cream in the fridge and the spices in the freezer – must be careful where I store things!",
        "When it comes to your diet during treatment, be cautious about what you eat or drink, avoiding acidic things and being mindful of your spice intake.",
        "After eating a burrito on my first day of chemo, I was a bit nervous since the salsa left my mouth a bit hot; I don't handle spices well.",
        "I was advised not to take turmeric in pill form during chemo, but incorporating it into foods in its spice form is allowed.",
        "Taking turmeric as a spice in warm water three times a day has cleared the boils for me; it's been quite effective.",
        "I prefer to put my spices in an old spice jar with big holes for easy access and usage.",
        "Planning to bake a spice cake and bring it down – hoping it lifts everyone's spirits!",
        "Consider an anti-inflammatory diet during chemo, focusing on foods like those in the Mediterranean diet, including lots of veggies, fruits, green tea, and spices such as turmeric, cinnamon, and ginger.",
        "Sticking to a diet with mostly no red meat, limited spices, and minimal alcohol has worked well for me during chemo.",
        "Chemo can sometimes magnify the taste of something, which is why mashed potatoes are a good choice – not too many spices in them.",
        "I have discovered that chemo can impact the taste of food, and sometimes avoiding overly spicy dishes is a good idea.",
        "Adding spices like cinnamon and nutmeg to my morning oatmeal has been a comforting way to start the day during treatment.",
        "Incorporating fresh herbs and spices into my meals has added flavor to my restricted diet during chemo.",
        "Finding creative ways to spice up bland foods has been a helpful strategy for maintaining a diverse diet during treatment.",
        "I've been experimenting with different spice blends to enhance the flavor of my meals without compromising my dietary restrictions.",
        "During chemo, I've learned to appreciate milder spices that don't irritate my taste buds too much.",
        "Incorporating ginger and other soothing spices into my tea has been a comforting ritual during treatment.",
        "I've been using a variety of spice-infused oils to add depth and flavor to my dishes without overwhelming my palate.",
        "Spicing up my meals with a touch of cayenne pepper or paprika has been a subtle way to add heat without causing discomfort.",
        "I've found that using a pinch of spice in my smoothies can be a creative way to make them more enjoyable during chemo.",
        "Avoiding overly spicy foods has been crucial for maintaining my digestive comfort during chemotherapy.",
        "I've developed a newfound appreciation for the subtle flavors of herbs and spices as I navigate the challenges of chemotherapy.",
        "Incorporating aromatic spices like cumin and coriander into my cooking has made the dining experience more enjoyable during treatment.",
        "Experimenting with spice rubs for grilled vegetables has been a tasty way to add variety to my chemo-friendly meals.",
        "I've learned to strike a balance with spices, opting for milder options to enhance the flavor without overwhelming my sensitive taste buds.",
        "Using spice-infused broths as a base for soups has been a flavorful and soothing choice for my chemo diet.",
        "Spicing up my snacks with a hint of chili powder or turmeric has been a satisfying way to enjoy treats within my dietary restrictions.",
        "I've found that choosing dishes with subtle spice profiles allows me to enjoy a diverse range of flavors without causing digestive discomfort.",
        "Incorporating warm spices like cinnamon and cardamom into my morning routine has added a comforting touch to my chemo days.",
        "I've discovered the joy of cooking with fresh herbs, finding that they bring a burst of flavor without relying on intense spices.",
        "Experimenting with spice blends has allowed me to tailor my meals to my taste preferences while still adhering to my dietary restrictions.",
        "Adding a dash of spice to my salads with a sprinkle of paprika or cayenne pepper has been a simple way to elevate their taste.",
        "I've learned to appreciate the subtle nuances of different spices, finding joy in discovering new ways to enhance my meals during chemo.",
        "Spicing up my morning smoothies with a hint of ginger or cinnamon has become a delightful ritual that adds flavor to my day.",
        "I've embraced the challenge of creating flavorful meals within the constraints of my chemo diet, exploring new spice combinations along the way.",
        "Choosing spice-infused dressings for my salads has been a delicious way to incorporate flavor without compromising my dietary restrictions.",
        "I've become more adventurous in my spice choices, exploring unique blends to add excitement to my chemo-friendly meals.",
        "Spicing up my desserts with a touch of cinnamon or nutmeg has been a simple yet satisfying way to enjoy sweet treats during treatment.",
        "I've found that incorporating a variety of spices into my meals allows me to enjoy a diverse and flavorful diet while undergoing chemotherapy.",
        "Experimenting with spice-infused teas has been a comforting and soothing ritual that adds warmth to my chemo days.",
        "I've learned to savor the subtle heat of spices like black pepper and cayenne, enjoying their presence without overwhelming my taste buds.",
        "Spicing up my beverages with a hint of ginger or mint has been a refreshing way to elevate my hydration routine during chemotherapy.",
        "I've discovered the joy of incorporating spices into my snacks, finding creative ways to add flavor without compromising my dietary restrictions."
    ],

	'Label':0,
	'Metaphor_ID':3
}

df_spice_no_metaphors = pd.DataFrame(data)




# Sample sentences without metaphors with the main word 'train'
sentences_train = [
    "I take the train to work every day.",
    "The train station was crowded during rush hour.",
    "She missed her train and had to wait for the next one.",
    "I enjoy the scenic views when traveling by train.",
    "The train schedule is convenient for my commute.",
    "The train conductor announced the upcoming stops.",
    "I prefer to read a book while on the train.",
    "The train journey was smooth and comfortable.",
    "I always find a seat on the train in the morning.",
    "The train ticket prices have increased recently.",
    "I usually listen to music on the train.",
    "The train platform was bustling with passengers.",
    "I met a friend while waiting for the train.",
    "The train arrived at the destination on time.",
    "The train compartment was well air-conditioned.",
    "The train tracks run parallel to the highway.",
    "I like to plan my train trips in advance.",
    "The train ticket includes a reserved seat.",
    "The train conductor checked our tickets.",
    "I prefer taking the train over driving in traffic.",
    "I appreciate the efficiency of the train schedule.",
    "The train conductor announced the next stop.",
    "I enjoy the comfort of the train seats.",
    "The train journey offers a break from driving.",
    "The train tracks run parallel to a beautiful river.",
    "I enjoy the convenience of the train station's proximity to my workplace.",
    "The train ride offers a sense of continuity and routine in my daily life.",
	"He is a yoga instructor, and even after his surgery, he plans to continue teaching his regular classes.",
        "Despite my recent surgery, I am determined to get back on the basketball court and train with my teammates.",
        "After overcoming a health setback, she is eager to resume her role as a dance instructor and train her students.",
        "Despite my recent illness, I am committed to returning to the gym and training with my workout partner.",
        "Having faced a health challenge, he is motivated to get back to the soccer field and train with his team.",
        "Even after chemotherapy, she is committed to returning to the basketball court and training with her teammates.",
        "After facing a health challenge, I am determined to get back to the swimming pool and train for upcoming competitions.",
        "Despite my recent health setback, I am eager to return to the tennis court and train with my doubles partner.",
        "She is a cycling enthusiast, and even after her surgery, she plans to return to the bike trails and train for her next race.",
        "After overcoming a health challenge, he is excited to get back on the soccer field and train with his team.",
]

# Create a DataFrame with a "Label" column set to 0 for sentences without metaphors
df_no_metaphors_train = pd.DataFrame({"Sentences": sentences_train, "Label": 0,'Metaphor_ID':5})

# Display the DataFrame


# Sample sentences without metaphors with the main word 'boat'
sentences_boat = [
    "We took a boat trip along the river on a sunny afternoon.",
    "The boat gently rocked as we sailed across the calm lake.",
    "He steered the boat with skill through the winding canals.",
    "A small boat was anchored near the sandy beach.",
    "Our family enjoyed a relaxing day on the boat, picnicking and swimming.",
    "She waved to us from the boat as it approached the dock.",
    "The boat captain shared interesting stories about the historical landmarks we passed.",
    "The boat's motor hummed softly as we glided through the water.",
    "We rented a rowboat and explored the peaceful pond.",
    "The boat's sails billowed in the wind, propelling us forward.",
    "We watched the sunset from the deck of the boat.",
    "A group of friends rented a yacht for a weekend adventure on the open sea.",
    "The boat crew provided life jackets for everyone on board.",
    "We spotted dolphins playing in the water during our boat tour.",
    "The boat's hull sliced through the waves effortlessly.",
    "The fisherman cast his net from the side of the boat.",
    "Our boat journey took us to a secluded island with white sandy beaches.",
    "The boat's navigation system guided us safely through the harbor.",
    "We admired the city skyline while cruising on the boat at night.",
    "The boat's anchor was dropped, and we enjoyed a quiet moment on the water.",
    "The boat's engine roared to life as we began our river expedition.",
    "We set sail on a catamaran for a thrilling sailing experience.",
    "The boat trip offered breathtaking views of the coastline.",
    "Children giggled with excitement during the boat ride at the amusement park.",
    "The boat's horn echoed across the lake, signaling our departure.",
    "We explored a hidden cove accessible only by boat.",
    "The boat gently rocked us to sleep under the starry night sky.",
    "The boat's captain navigated skillfully through the narrow channel.",
    "A fleet of colorful sailboats dotted the horizon during the regatta.",
    "The boat tour provided a close-up view of the historic lighthouse.",
    "We rented a paddleboat and leisurely paddled around the pond.",
    "The boat's crewmembers assisted passengers with boarding.",
    "The boat journey through the mangrove forest was a serene nature experience.",
    "We joined a guided boat excursion to discover the rich marine life.",
    "The boat's hull gleamed in the sunlight as we cruised along the coast.",
    "We participated in a team-building activity on a rowing boat.",
    "The boat's horn signaled our arrival at the bustling harbor.",
    "We marveled at the intricate details of the traditional wooden boat.",
    "The boat captain shared interesting facts about the local marine ecosystem.",
    "Our boat adventure included a visit to a charming fishing village.",
    "The boat's wake left a mesmerizing trail on the water's surface.",
    "We rented a canoe and explored the peaceful river delta.",
    "The boat trip offered stunning views of the sunrise over the water.",
    "Children eagerly gathered at the front of the boat to spot marine life.",
    "We embarked on a catamaran cruise for a day of relaxation and snorkeling.",
    "The boat's crew provided informative commentary on the coastal landmarks.",
    "We navigated through narrow canals on a traditional gondola boat.",
    "We anchored the boat near a pristine sandy beach for a relaxing afternoon.",
    "The boat's bow pointed toward the horizon as we set sail for an island getaway.",
    "We embarked on a historic boat tour to learn about the city's maritime heritage.",
    "The boat ride provided a unique perspective of the coastal cliffs.",
    "We joined a guided boat safari to spot exotic birds along the riverbanks.",
    "The boat's captain skillfully maneuvered through a challenging sea passage.",
    "We explored a mangrove estuary on an eco-friendly electric boat.",
    "The boat's navigation system guided us through a labyrinth of canals.",
    "We anchored the boat in a tranquil lagoon surrounded by lush vegetation.",
    "The boat ride offered glimpses of marine life beneath the crystal-clear water.",
    "We set sail on a historic schooner for a nostalgic journey on the high seas.",
    "The boat's deck provided a perfect vantage point for birdwatching.",
    "We ventured on a speedboat tour, experiencing thrilling maneuvers.",
    "The boat's wake created mesmerizing patterns on the surface of the lake.",
    "We joined a boat parade to celebrate a festive maritime event.",
    "The boat's anchor was lifted, and we set out for a day of island hopping.",
    "We explored a network of underground caves accessible only by boat.",
    "The boat's crewmembers demonstrated traditional fishing techniques.",
    "We enjoyed a sunset cruise, watching the sky transform into vibrant hues.",
    "The boat's navigation lights guided us safely back to the harbor after dark.",
    "We embarked on a traditional wooden dhow boat for an Arabian Gulf excursion.",
    "The boat ride provided a front-row seat to a spectacular fireworks display.",
]

# Create a DataFrame with sentences and label them as 0 (no metaphors)
df_boat_no_metaphor = pd.DataFrame({"Sentences": sentences_boat, "Label": 0,'Metaphor_ID':6})

# Display the DataFrame


new_updated_df = pd.concat([
    df_road_no_metaphor,
df_no_metaphor_candle,
df_candle_metaphor,
df_patient_metaphors_spice,
df_spice_no_metaphors,
df_no_metaphors_train,
df_boat_no_metaphor
], ignore_index=True)




import pandas as pd
import spacy
import re

# Load the spaCy English language model
nlp = spacy.load('en_core_web_sm')
def spacy_lemmatize(text):
    text=text.lower()
    text = re.sub(r'\?+', '?', text)
    text = re.sub(r'\!+', '!', text)
    text = re.sub(r'\/+', '', text)
    text = re.sub(r'\-+', '-', text)
    text = re.sub(r'`', '', text)
    text = re.sub(r'-lrb-', '-', text)
    text = re.sub(r'-rrb-', '-', text)
    text = re.sub(r"I've", "i have", text)
    text = re.sub(r"i've", "i have", text)
    text = re.sub(r"I'm", "i am", text)
    text = re.sub(r"i'm", "i am", text)
    text = re.sub(r"i 'm", "i am", text)
    text = re.sub(r"i 've", "i have", text)
    doc = nlp(text)
    lemmatized_tokens = [token.lemma_ for token in doc]
    lemmatized_text = ' '.join(lemmatized_tokens)
    lemmatized_text = re.sub(r"'s\b", "s", lemmatized_text)
    return lemmatized_text



new_updated_df['lemmatized_text'] = new_updated_df['Sentences'].apply(spacy_lemmatize)


important_sentences = []

for index, row in new_updated_df.iterrows():
    text = ""  # Initialize an empty string

    if row['Metaphor_ID'] == 0:
        keyword_search = 'road'
    elif row['Metaphor_ID'] == 1:
        keyword_search = 'candle'
    elif row['Metaphor_ID'] == 2:
        keyword_search = 'light'
    elif row['Metaphor_ID'] == 3:
        keyword_search = 'spice'
    elif row['Metaphor_ID'] == 4:
        keyword_search = 'ride'
    elif row['Metaphor_ID'] == 5:
        keyword_search = 'train'
    elif row['Metaphor_ID'] == 6:
        keyword_search = 'boat'

    for j in row['lemmatized_text'].split('.'):



        if keyword_search in j:
            if (' - ' not in j) and (' , ' not in j) and (' ; ' not in j) and (' ? ' not in j) and (' ! ' not in j):
                if keyword_search in j:
                        text = j
                        break

            elif ' , ' in j:
                for k in j.split(','):
                    if keyword_search in k:
                        text = k
                        break
            elif ' ; ' in j:
                for k in j.split(';'):
                    if keyword_search in k:
                        text = k
                        break
            elif ' ? ' in j:
                for k in j.split(' ? '):
                    if keyword_search in k:
                        text = k
                        break
            elif ' ! ' in j:
                for k in j.split(' ! '):
                    if keyword_search in k:
                        text = k
                        break
            elif ' - ' in j:
                for k in j.split(' - '):
                    if keyword_search in k:
                        text = k
                        break

    if text:
        important_sentences.append(text)

train_text=new_updated_df['Sentences'].to_list()
train_labels=new_updated_df['Label'].to_list()
X_train=X_train+train_text
y_train=y_train+train_labels

# Load pre-trained BERT model and tokenizer
model_name = 'bert-base-uncased'
tokenizer = BertTokenizer.from_pretrained(model_name)
bert_model = BertModel.from_pretrained(model_name)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
bert_model.to(device)
embeddings = []
for sentence in X_train:
    tokens = tokenizer(sentence, return_tensors='pt', padding=True, truncation=True)
    with torch.no_grad():
        # Move tokens to GPU
        for key in tokens:
            tokens[key] = tokens[key].to(device)

        outputs = bert_model(**tokens)
    cls_embedding = outputs.last_hidden_state[:, 0, :].cpu().numpy()
    embeddings.append(cls_embedding)

# Convert the list of embeddings to a numpy array
embeddings = np.array(embeddings)


embeddings_test = []

for sentence in X_test:
    tokens = tokenizer(sentence, return_tensors='pt', padding=True, truncation=True)
    with torch.no_grad():
      for key in tokens:
            tokens[key] = tokens[key].to(device)
      outputs = bert_model(**tokens)
    cls_embedding = outputs.last_hidden_state[:, 0, :].cpu().numpy()
    embeddings_test.append(cls_embedding)

# Convert the list of embeddings to a numpy array
embeddings_test = np.array(embeddings_test)

model_LSTM = tf.keras.Sequential([


    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64), input_shape=(embeddings.shape[1], embeddings.shape[2])),
    tf.keras.layers.Dense(216, activation='relu'),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(108, activation='relu'),
    tf.keras.layers.Dense(108, activation='relu'),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(54, activation='relu'),
    tf.keras.layers.Dense(28, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Define model checkpoint callback
early_stopping = EarlyStopping(monitor='val_accuracy', patience=100, restore_best_weights=True)

# Define model checkpoint callback
model_checkpoint = ModelCheckpoint('best_model.h5', monitor='val_accuracy', save_best_only=True)

training_labels = np.array(y_train)

testing_labels = np.array(y_test)
model_LSTM.compile(loss='binary_crossentropy',optimizer=Adam(learning_rate=0.000005),metrics=['accuracy'])
num_epochs = 350
history = model_LSTM.fit(embeddings, training_labels, epochs=num_epochs, validation_data=(embeddings_test, testing_labels), verbose=1,callbacks=[early_stopping, model_checkpoint])

y_pred=np.round(model_LSTM.predict(embeddings_test))
y_pred=y_pred.flatten()
from sklearn.metrics import classification_report
# Generate classification report
report = classification_report( testing_labels,y_pred)

# Print the classification report
print("Classification Report:\n", report)

